[2020-07-07 10:41:03,826] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /index/ HTTP/1.1" 200 10120
[2020-07-07 10:41:04,011] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/login/js/echarts.min.js HTTP/1.1" 200 383547
[2020-07-07 10:41:20,278] [base.py:93] [base:get_response] [WARNING]- Not Found: /favicon.ico
[2020-07-07 10:41:20,279] [basehttp.py:124] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 6234
[2020-07-07 10:42:29,788] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /test_report_list10/ HTTP/1.1" 200 10364
[2020-07-07 10:42:29,878] [base.py:93] [base:get_response] [WARNING]- Not Found: /api/echarts
[2020-07-07 10:42:29,879] [basehttp.py:124] [basehttp:log_message] [WARNING]- "GET /api/echarts HTTP/1.1" 404 6234
[2020-07-07 10:43:14,922] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /test_report_list10/ HTTP/1.1" 200 10227
[2020-07-07 10:43:14,994] [base.py:93] [base:get_response] [WARNING]- Not Found: /api/echarts
[2020-07-07 10:43:14,994] [basehttp.py:124] [basehttp:log_message] [WARNING]- "GET /api/echarts HTTP/1.1" 404 6234
[2020-07-07 10:45:34,883] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /test_report_list10/ HTTP/1.1" 200 10227
[2020-07-07 10:45:34,972] [base.py:93] [base:get_response] [WARNING]- Not Found: /api/echarts
[2020-07-07 10:45:34,973] [basehttp.py:124] [basehttp:log_message] [WARNING]- "GET /api/echarts HTTP/1.1" 404 6234
[2020-07-07 10:46:01,162] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /test_report_list10/ HTTP/1.1" 200 10227
[2020-07-07 10:46:01,235] [base.py:93] [base:get_response] [WARNING]- Not Found: /api/echarts
[2020-07-07 10:46:01,236] [basehttp.py:124] [basehttp:log_message] [WARNING]- "GET /api/echarts HTTP/1.1" 404 6234
[2020-07-07 10:46:53,044] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /test_report_list10/ HTTP/1.1" 200 10227
[2020-07-07 10:46:53,144] [base.py:93] [base:get_response] [WARNING]- Not Found: /api/echarts
[2020-07-07 10:46:53,144] [basehttp.py:124] [basehttp:log_message] [WARNING]- "GET /api/echarts HTTP/1.1" 404 6234
[2020-07-07 10:47:21,960] [base.py:93] [base:get_response] [WARNING]- Not Found: /api/echarts
[2020-07-07 10:47:21,961] [basehttp.py:124] [basehttp:log_message] [WARNING]- "GET /api/echarts HTTP/1.1" 404 6234
[2020-07-07 10:48:10,569] [base.py:93] [base:get_response] [WARNING]- Not Found: /api_test
[2020-07-07 10:48:10,570] [basehttp.py:124] [basehttp:log_message] [WARNING]- "GET /api_test HTTP/1.1" 404 6225
[2020-07-07 10:49:29,129] [base.py:93] [base:get_response] [WARNING]- Not Found: /index
[2020-07-07 10:49:29,130] [basehttp.py:124] [basehttp:log_message] [WARNING]- "GET /index HTTP/1.1" 404 6216
[2020-07-07 10:49:33,434] [base.py:93] [base:get_response] [WARNING]- Not Found: /index
[2020-07-07 10:49:33,435] [basehttp.py:124] [basehttp:log_message] [WARNING]- "GET /index HTTP/1.1" 404 6216
[2020-07-07 10:49:44,755] [base.py:93] [base:get_response] [WARNING]- Not Found: /index
[2020-07-07 10:49:44,756] [basehttp.py:124] [basehttp:log_message] [WARNING]- "GET /index HTTP/1.1" 404 6216
[2020-07-07 10:49:45,605] [base.py:93] [base:get_response] [WARNING]- Not Found: /index
[2020-07-07 10:49:45,605] [basehttp.py:124] [basehttp:log_message] [WARNING]- "GET /index HTTP/1.1" 404 6216
[2020-07-07 10:49:46,144] [base.py:93] [base:get_response] [WARNING]- Not Found: /index
[2020-07-07 10:49:46,145] [basehttp.py:124] [basehttp:log_message] [WARNING]- "GET /index HTTP/1.1" 404 6216
[2020-07-07 10:49:46,304] [base.py:93] [base:get_response] [WARNING]- Not Found: /index
[2020-07-07 10:49:46,305] [basehttp.py:124] [basehttp:log_message] [WARNING]- "GET /index HTTP/1.1" 404 6216
[2020-07-07 10:49:46,324] [basehttp.py:124] [basehttp:log_message] [ERROR]- "GET /index HTTP/1.1" 500 59
[2020-07-07 10:49:46,452] [base.py:93] [base:get_response] [WARNING]- Not Found: /index
[2020-07-07 10:49:46,452] [basehttp.py:124] [basehttp:log_message] [WARNING]- "GET /index HTTP/1.1" 404 6216
[2020-07-07 10:49:46,608] [base.py:93] [base:get_response] [WARNING]- Not Found: /index
[2020-07-07 10:49:46,609] [basehttp.py:124] [basehttp:log_message] [WARNING]- "GET /index HTTP/1.1" 404 6216
[2020-07-07 10:49:46,792] [base.py:93] [base:get_response] [WARNING]- Not Found: /index
[2020-07-07 10:49:46,793] [basehttp.py:124] [basehttp:log_message] [WARNING]- "GET /index HTTP/1.1" 404 6216
[2020-07-07 10:49:46,944] [base.py:93] [base:get_response] [WARNING]- Not Found: /index
[2020-07-07 10:49:46,945] [basehttp.py:124] [basehttp:log_message] [WARNING]- "GET /index HTTP/1.1" 404 6216
[2020-07-07 10:52:37,840] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /test_report_list10/ HTTP/1.1" 200 10227
[2020-07-07 10:52:37,978] [base.py:93] [base:get_response] [WARNING]- Not Found: /api/echarts
[2020-07-07 10:52:37,979] [basehttp.py:124] [basehttp:log_message] [WARNING]- "GET /api/echarts HTTP/1.1" 404 6234
[2020-07-07 10:52:46,811] [base.py:93] [base:get_response] [WARNING]- Not Found: /index
[2020-07-07 10:52:46,812] [basehttp.py:124] [basehttp:log_message] [WARNING]- "GET /index HTTP/1.1" 404 6216
[2020-07-07 10:56:16,267] [base.py:93] [base:get_response] [WARNING]- Not Found: /index
[2020-07-07 10:56:16,268] [basehttp.py:124] [basehttp:log_message] [WARNING]- "GET /index HTTP/1.1" 404 6216
[2020-07-07 10:56:16,792] [base.py:93] [base:get_response] [WARNING]- Not Found: /index
[2020-07-07 10:56:16,793] [basehttp.py:124] [basehttp:log_message] [WARNING]- "GET /index HTTP/1.1" 404 6216
[2020-07-07 10:56:17,616] [base.py:93] [base:get_response] [WARNING]- Not Found: /index
[2020-07-07 10:56:17,617] [basehttp.py:124] [basehttp:log_message] [WARNING]- "GET /index HTTP/1.1" 404 6216
[2020-07-07 10:56:47,454] [base.py:93] [base:get_response] [WARNING]- Not Found: /add_cases
[2020-07-07 10:56:47,455] [basehttp.py:124] [basehttp:log_message] [WARNING]- "GET /add_cases HTTP/1.1" 404 6228
[2020-07-07 11:02:55,384] [base.py:93] [base:get_response] [WARNING]- Not Found: /add_cases
[2020-07-07 11:02:55,385] [basehttp.py:124] [basehttp:log_message] [WARNING]- "GET /add_cases HTTP/1.1" 404 6229
[2020-07-07 11:02:59,326] [base.py:93] [base:get_response] [WARNING]- Not Found: /index/
[2020-07-07 11:02:59,327] [basehttp.py:124] [basehttp:log_message] [WARNING]- "GET /index/ HTTP/1.1" 404 6220
[2020-07-07 11:04:04,382] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /api/echarts/ HTTP/1.1" 200 581
[2020-07-07 11:04:59,700] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /api/echarts/ HTTP/1.1" 200 581
[2020-07-07 11:05:00,731] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /api/echarts/ HTTP/1.1" 200 581
[2020-07-07 11:05:01,880] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /api/echarts/ HTTP/1.1" 200 581
[2020-07-07 11:05:02,224] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /api/echarts/ HTTP/1.1" 200 581
[2020-07-07 11:05:04,112] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /api/echarts/ HTTP/1.1" 200 581
[2020-07-07 11:05:04,601] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /api/echarts/ HTTP/1.1" 200 581
[2020-07-07 11:05:05,579] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /api/echarts/ HTTP/1.1" 200 581
[2020-07-07 11:05:06,102] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /api/echarts/ HTTP/1.1" 200 581
[2020-07-07 11:05:13,702] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /index/ HTTP/1.1" 200 10121
[2020-07-07 11:05:19,859] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /index/ HTTP/1.1" 200 10121
[2020-07-07 11:05:20,720] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /index/ HTTP/1.1" 200 10121
[2020-07-07 11:05:21,605] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /index/ HTTP/1.1" 200 10121
[2020-07-07 11:05:22,674] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /index/ HTTP/1.1" 200 10121
[2020-07-07 11:05:23,546] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /index/ HTTP/1.1" 200 10121
[2020-07-07 11:05:25,748] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /index/ HTTP/1.1" 200 10121
[2020-07-07 11:05:32,966] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /index/ HTTP/1.1" 200 10121
[2020-07-07 11:05:33,889] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /index/ HTTP/1.1" 200 10121
[2020-07-07 11:05:40,309] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /index/ HTTP/1.1" 200 10121
[2020-07-07 11:05:43,936] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /index/ HTTP/1.1" 200 10121
[2020-07-07 11:05:58,401] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /test_report_list10/ HTTP/1.1" 200 9871
[2020-07-07 11:05:58,506] [base.py:93] [base:get_response] [WARNING]- Not Found: /api/echarts
[2020-07-07 11:05:58,507] [basehttp.py:124] [basehttp:log_message] [WARNING]- "GET /api/echarts HTTP/1.1" 404 6234
[2020-07-07 11:06:51,948] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /test_report_list10/ HTTP/1.1" 200 9871
[2020-07-07 11:06:52,039] [base.py:93] [base:get_response] [WARNING]- Not Found: /api/echarts
[2020-07-07 11:06:52,040] [basehttp.py:124] [basehttp:log_message] [WARNING]- "GET /api/echarts HTTP/1.1" 404 6106
[2020-07-07 11:07:10,281] [base.py:93] [base:get_response] [WARNING]- Not Found: /api/echarts
[2020-07-07 11:07:10,282] [basehttp.py:124] [basehttp:log_message] [WARNING]- "GET /api/echarts HTTP/1.1" 404 6106
[2020-07-07 11:07:22,003] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /api/echarts/ HTTP/1.1" 200 581
[2020-07-07 11:07:31,030] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /api/echarts/ HTTP/1.1" 200 581
[2020-07-07 11:07:49,767] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /test_report_list10/ HTTP/1.1" 200 9872
[2020-07-07 11:07:50,069] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /api/echarts/ HTTP/1.1" 200 581
[2020-07-07 11:08:24,758] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /test_report_list10/ HTTP/1.1" 200 9872
[2020-07-07 11:08:25,027] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /api/echarts/ HTTP/1.1" 200 581
[2020-07-07 11:10:34,933] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /test_report_list10/ HTTP/1.1" 200 10364
[2020-07-07 11:10:35,027] [base.py:93] [base:get_response] [WARNING]- Not Found: /api/echarts
[2020-07-07 11:10:35,027] [basehttp.py:124] [basehttp:log_message] [WARNING]- "GET /api/echarts HTTP/1.1" 404 6234
[2020-07-07 11:10:47,764] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /test_report_list10/ HTTP/1.1" 200 10365
[2020-07-07 11:10:48,052] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /api/echarts/ HTTP/1.1" 200 581
[2020-07-07 11:10:51,678] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /index/ HTTP/1.1" 200 10132
[2020-07-07 11:10:52,451] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /index/ HTTP/1.1" 200 10132
[2020-07-07 11:10:53,550] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /index/ HTTP/1.1" 200 10132
[2020-07-07 11:55:32,853] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /add_buy_share/ HTTP/1.1" 200 2833
[2020-07-07 11:55:33,009] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/login/css/send_vip.css HTTP/1.1" 200 609
[2020-07-07 11:57:18,589] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /add_buy_share/ HTTP/1.1" 200 2833
[2020-07-07 11:57:19,859] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /index/ HTTP/1.1" 200 10132
[2020-07-07 11:57:20,883] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /index/ HTTP/1.1" 200 10132
[2020-07-07 11:57:21,989] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /add_buy_share/ HTTP/1.1" 200 2833
[2020-07-07 11:57:23,447] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /add_buy_share/ HTTP/1.1" 200 2833
[2020-07-07 11:58:05,526] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /add_buy_share/ HTTP/1.1" 200 2833
[2020-07-07 11:58:06,774] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /add_buy_share/ HTTP/1.1" 200 2833
[2020-07-07 11:58:14,085] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /index/ HTTP/1.1" 200 10132
[2020-07-07 14:09:43,032] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /index/ HTTP/1.1" 200 10132
[2020-07-07 14:54:34,782] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /index/ HTTP/1.1" 200 10132
[2020-07-07 15:53:00,128] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /index/ HTTP/1.1" 200 10132
[2020-07-07 15:53:02,333] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /test_report_list10/ HTTP/1.1" 200 10365
[2020-07-07 15:53:03,878] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /api/echarts/ HTTP/1.1" 200 601
[2020-07-07 15:53:18,036] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /test_report_list10/ HTTP/1.1" 200 10365
[2020-07-07 15:53:20,017] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /api/echarts/ HTTP/1.1" 200 600
[2020-07-07 15:54:02,727] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /test_report_list10/ HTTP/1.1" 200 10365
[2020-07-07 15:54:04,140] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /api/echarts/ HTTP/1.1" 200 220
[2020-07-07 15:54:14,457] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /test_report_list10/ HTTP/1.1" 200 10365
[2020-07-07 15:54:15,867] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /api/echarts/ HTTP/1.1" 200 501
[2020-07-07 15:54:23,804] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /test_report_list10/ HTTP/1.1" 200 10365
[2020-07-07 15:54:25,208] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /api/echarts/ HTTP/1.1" 200 380
[2020-07-07 15:55:22,589] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /test_report_list10/ HTTP/1.1" 200 10365
[2020-07-07 15:55:24,042] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /api/echarts/ HTTP/1.1" 200 380
[2020-07-07 15:55:31,037] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /test_report_list10/ HTTP/1.1" 200 10365
[2020-07-07 15:55:32,501] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /api/echarts/ HTTP/1.1" 200 501
[2020-07-07 15:56:08,062] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /test_report_list10/ HTTP/1.1" 200 10365
[2020-07-07 15:56:09,250] [exception.py:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /api/echarts/
Traceback (most recent call last):
  File "D:\Programs\Python\Python37\Lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\Programs\Python\Python37\Lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Programs\Python\Python37\Lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\PycharmProjects\MyPro1\login\views.py", line 216, in echarts_data
    five_week = datetime.datetime.now().date() - datetime.timedelta(month=1)
TypeError: 'month' is an invalid keyword argument for __new__()
[2020-07-07 15:56:09,283] [basehttp.py:124] [basehttp:log_message] [ERROR]- "GET /api/echarts/ HTTP/1.1" 500 18536
[2020-07-07 15:56:24,237] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /test_report_list10/ HTTP/1.1" 200 10365
[2020-07-07 15:56:25,839] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /api/echarts/ HTTP/1.1" 200 501
[2020-07-07 15:57:38,128] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /test_report_list10/ HTTP/1.1" 200 10365
[2020-07-07 15:57:39,589] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /api/echarts/ HTTP/1.1" 200 400
[2020-07-07 15:58:13,777] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /test_report_list10/ HTTP/1.1" 200 10365
[2020-07-07 15:58:15,213] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /api/echarts/ HTTP/1.1" 200 601
[2020-07-07 15:58:29,003] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /test_report_list10/ HTTP/1.1" 200 10365
[2020-07-07 15:58:30,431] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /api/echarts/ HTTP/1.1" 200 601
[2020-07-07 15:59:20,351] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /test_report_list10/ HTTP/1.1" 200 10365
[2020-07-07 15:59:21,967] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /api/echarts/ HTTP/1.1" 200 601
[2020-07-07 15:59:54,680] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /test_report_list10/ HTTP/1.1" 200 10365
[2020-07-07 15:59:56,097] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /api/echarts/ HTTP/1.1" 200 400
[2020-07-07 18:53:52,357] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /index/ HTTP/1.1" 200 10132
[2020-07-07 18:53:53,973] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /mail_config_manual/ HTTP/1.1" 200 2089
[2020-07-07 18:53:59,105] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /run_test/ HTTP/1.1" 200 2888
[2020-07-07 18:53:59,332] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/login/css/run_test.css HTTP/1.1" 200 634
[2020-07-07 18:54:03,291] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /run_test/ HTTP/1.1" 200 2888
[2020-07-07 18:54:28,994] [exception.py:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /run_test/
Traceback (most recent call last):
  File "D:\Programs\Python\Python37\Lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\Programs\Python\Python37\Lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Programs\Python\Python37\Lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Programs\Python\Python37\Lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\PycharmProjects\MyPro1\login\viewas\test_view\autotest_view.py", line 137, in run_test
    msg_robot(message, robotKey)
  File "D:\PycharmProjects\MyPro1\login\templates\utils\wechat_robot.py", line 37, in msg_robot
    json=data
  File "D:\Programs\Python\Python37\Lib\site-packages\requests\api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "D:\Programs\Python\Python37\Lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Programs\Python\Python37\Lib\site-packages\requests\sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "D:\Programs\Python\Python37\Lib\site-packages\requests\sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "D:\Programs\Python\Python37\Lib\site-packages\requests\models.py", line 305, in prepare
    self.prepare_url(url, params)
  File "D:\Programs\Python\Python37\Lib\site-packages\requests\models.py", line 379, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '15cdf3d2-80fd-4c1c-b648-33f500ab73ef': No schema supplied. Perhaps you meant http://15cdf3d2-80fd-4c1c-b648-33f500ab73ef?
[2020-07-07 18:54:29,133] [basehttp.py:124] [basehttp:log_message] [ERROR]- "GET /run_test/?csrfmiddlewaretoken=R9XcEikhOXeBcQsx3YZ6tuAslB92tjxXstmWxZzRYVaGR2R5YViJNfsPuO447uGD&test_type=Nec&envId=4&project=yyting-apps-api HTTP/1.1" 500 122988
[2020-07-07 18:56:50,899] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /run_test/?csrfmiddlewaretoken=R9XcEikhOXeBcQsx3YZ6tuAslB92tjxXstmWxZzRYVaGR2R5YViJNfsPuO447uGD&test_type=Nec&envId=4&project=yyting-apps-api HTTP/1.1" 200 99
[2020-07-07 19:00:52,301] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /run_test/?csrfmiddlewaretoken=R9XcEikhOXeBcQsx3YZ6tuAslB92tjxXstmWxZzRYVaGR2R5YViJNfsPuO447uGD&test_type=Nec&envId=4&project=yyting-apps-api HTTP/1.1" 200 84
[2020-07-07 19:02:36,759] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /run_test/?csrfmiddlewaretoken=R9XcEikhOXeBcQsx3YZ6tuAslB92tjxXstmWxZzRYVaGR2R5YViJNfsPuO447uGD&test_type=Nec&envId=4&project=yyting-apps-api HTTP/1.1" 200 99
[2020-07-07 19:13:25,308] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /run_test/?csrfmiddlewaretoken=R9XcEikhOXeBcQsx3YZ6tuAslB92tjxXstmWxZzRYVaGR2R5YViJNfsPuO447uGD&test_type=Nec&envId=4&project=yyting-apps-api HTTP/1.1" 200 84
[2020-07-07 19:15:28,706] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /index/ HTTP/1.1" 200 10132
[2020-07-07 19:15:31,504] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /index/ HTTP/1.1" 200 10132
[2020-07-07 19:18:10,558] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /run_test/ HTTP/1.1" 200 2888
[2020-07-07 19:18:14,687] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /run_test/ HTTP/1.1" 200 2888
[2020-07-07 19:18:47,860] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /run_test/?csrfmiddlewaretoken=iuDvjRhhULYScCYKijy6i4Z6srqUH2uLTO2fcywR4JUXROnidgRJCPRtBElWldDr&test_type=All&envId=4&project=yyting-apps-api HTTP/1.1" 200 98
