[2020-06-12 11:26:34,006] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /mail_config_manual/ HTTP/1.1" 200 2089
[2020-06-12 11:26:53,773] [exception.py:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /mail_config_manual/
Traceback (most recent call last):
  File "D:\Programs\Python\Python37\Lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\Programs\Python\Python37\Lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Programs\Python\Python37\Lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\PycharmProjects\MyPro1\login\viewas\test_view\autotest_view.py", line 255, in mail_config_manual
    return redirect('/index/')
  File "D:\Programs\Python\Python37\Lib\site-packages\django\shortcuts.py", line 58, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
  File "D:\Programs\Python\Python37\Lib\site-packages\django\shortcuts.py", line 149, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "D:\Programs\Python\Python37\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "D:\Programs\Python\Python37\Lib\site-packages\django\urls\resolvers.py", line 565, in _reverse_with_prefix
    self._populate()
  File "D:\Programs\Python\Python37\Lib\site-packages\django\urls\resolvers.py", line 416, in _populate
    for url_pattern in reversed(self.url_patterns):
TypeError: 'set' object is not reversible
[2020-06-12 11:26:54,240] [basehttp.py:124] [basehttp:log_message] [ERROR]- "POST /mail_config_manual/ HTTP/1.1" 500 97081
[2020-06-12 11:29:44,665] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /mail_config_manual/ HTTP/1.1" 302 0
[2020-06-12 11:29:45,960] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /index/ HTTP/1.1" 200 10121
